# Standard Configuration YAML
command-name: "ping"
description: "Ping a destination address"
keep-alive: false
flags:
  ## The "count" option specifies the number of pings to send.
  count:
    description: "Number of pings to send"
    type: "string"
    required: true
    prefix: "-c"
  # The "timeout" option specifies the maximum time to wait for a response, in seconds.
  timeout:
    description: "Maximum time to wait for a response, in seconds"
    type: "string"
    required: true
    prefix: "-W"
  # The "destination" option specifies the destination address to ping.
  destination:
    description: "Destination address to ping"
    type: "string"
    required: true